### ISSUE TITLE
UTF 8 conversion error

### ISSUE THREAD

**Issue by stdx** [zlElo/Froggius#3]
```
Traceback (most recent call last):
  File "...\dev\temp\src\main.py", line 39, in <module>
    logger.info("\nFinished process ✓")
  File ...p\confluence_export\venv\Lib\site-packages\froggius\logger.py", line 210, in info
    return self.information(log_msg, file_path, highlighting, print_out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "....mp\confluence_export\venv\Lib\site-packages\froggius\logger.py", line 195, in information
    log.write(
  File ....\python\current\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 49: character maps to <undefined>
```

Seems like an UTF-8 conversion error. Please have a look.

**Comment by zlElo** [comment]
Actually, not a UTF-8 conversion error! It's a problem with the `\n` for a new line. I tested it with the latest stable version (0.1.7) and on my system it's working.

Greets 🍕
